### ISSUE TITLE
SRTools[星轨工具箱]现支持SRGF标准

### ISSUE THREAD

**Issue by JamXi233** [UIGF-org/UIGF-org.github.io#25]
项目地址:[SRTools](https://github.com/JamXi233/SRTools)
**JSG-JamXi致上**

**Comment by Lightczx** [comment]
你就说抄没抄Starward吧（

**Comment by JamXi233** [comment]
> 你就说抄没抄Starward吧（

还真不是，毕竟做启动器的话界面都是差不多的
如果说SRTools是抄的Starward，有没有可能Starward抄的Collapse呢 [小声]（

**Comment by Lightczx** [comment]
@Masterain98 FYI

**Comment by JamXi233** [comment]
刚才注意到了Starward的README写了灵感来自于Collapse
