### ISSUE TITLE
提瓦特小助手事实上并未支持UIGF格式

### ISSUE THREAD

**Issue by char-46** [UIGF-org/UIGF-org.github.io#5]
RT

**Comment by Lightczx** [comment]
你导入了什么软件

**Comment by char-46** [comment]
我从其他软件导入。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："DismissedLight ***@***.***&gt;;
发送时间：2023年4月1日(星期六) 晚上7:50
收件人："UIGF-org/UIGF-org.github.io" ***@***.***&gt;;
抄送："char46 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [UIGF-org/UIGF-org.github.io] 提瓦特小助手事实上并未支持UIGF格式 (Issue #5)
-----------------------------------

 

 
你导入了什么软件

**Comment by Lightczx** [comment]
@zzpro

**Comment by zzpro** [comment]
@char-46 https://api.lelaer.com/ys/uploadGacha.php  上传UIGF格式的josn文件即可导入

**Comment by char-46** [comment]
是否可以作为小程序的一部分，如‘如何获取抽卡分析地址’按钮下方添加导入链接？@zzpro

**Comment by zzpro** [comment]
@char-46 目前还没有全量开放，是因json文件存在被修改的可能性，例如将你的UID改成他人的UID，上传后将会影响到他人的抽卡记录。

后续版本会进行迭代，根据抽卡分析url+json文件方式，先对UID进行鉴权再后导入记录。

**Comment by char-46** [comment]
好的，感谢解答疑惑。

**Comment by zzpro** [comment]
@char-46 抽卡记录导入和导入的UID鉴权功能已经完成，欢迎测试 https://api.lelaer.com/ys/uploadGacha.php

灰度测试一段时间，确认没有问题后，会全量开放
