### ISSUE TITLE
原神获取抽卡记录的接口更新了吗

### ISSUE THREAD

**Issue by biuuu** [UIGF-org/UIGF-org.github.io#54]
抓包看到新的 URL 是 `https://public-operation-hk4e.mihoyo.com/gacha_info/api/getGachaLog` ，
国际服是否也是这个域名呢？

**Comment by Masterain98** [comment]
国际服当前的 URL 是 `https://hk4e-api-os.hoyoverse.com/gacha_info/api/getGachaLog?`
