### ISSUE TITLE
Netlify强制转换为小写导致含大写字母页面直接访问转跳到404

### ISSUE THREAD

**Issue by MUKAPP** [UIGF-org/UIGF-org.github.io#60]
从其他页面直接点UIGF API是没有问题的，但是如果在新窗口中打开链接，或者刷新页面，都会404
![image](https://github.com/UIGF-org/UIGF-org.github.io/assets/41848070/24016a7a-2952-4bc9-8017-5e208d98a237)

**Comment by LaoshuBaby** [comment]
可复现

直接输入 https://uigf.org/zh/API.html 这个网址访问，在Chrome中会被认为是访问 https://uigf.org/zh/api.html

![图片](https://github.com/UIGF-org/UIGF-org.github.io/assets/42690037/0f7e3e3b-5c0d-44f2-9f90-08b8a1ca9c10)

而在首页上点UIGF API跳转到的就是正常的

![图片](https://github.com/UIGF-org/UIGF-org.github.io/assets/42690037/951a8d7d-09a8-4c96-a9a5-75da5f44c3ee)
